-- Migration: Schema updates for departments, staff availability, class size, and room capacity
-- Date: 2026-02-13

-- 1) Departments table
CREATE TABLE IF NOT EXISTS public.departments (
  department_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL UNIQUE
);

-- 2) Staff-Department mapping (many-to-many)
CREATE TABLE IF NOT EXISTS public.staff_dept_map (
  staff_dept_map_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id integer NOT NULL,
  department_id integer NOT NULL,
  is_active boolean DEFAULT true,
  CONSTRAINT staff_dept_map_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(staff_id),
  CONSTRAINT staff_dept_map_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(department_id)
);

-- 3) Staff availability (recurring or date-specific blocks)
CREATE TABLE IF NOT EXISTS public.staff_availability (
  availability_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id integer NOT NULL,
  timeslot_id integer NOT NULL,
  is_recurring boolean NOT NULL,
  day_of_week character varying,
  date date,
  reason text,
  is_active boolean DEFAULT true,
  CONSTRAINT staff_availability_staff_id_fkey FOREIGN KEY (staff_id) REFERENCES public.staff(staff_id),
  CONSTRAINT staff_availability_timeslot_id_fkey FOREIGN KEY (timeslot_id) REFERENCES public.timeslots(timeslot_id),
  CONSTRAINT staff_availability_recurring_check CHECK (
    (is_recurring = true AND day_of_week IS NOT NULL AND date IS NULL)
    OR (is_recurring = false AND date IS NOT NULL)
  )
);

-- 4) Add class_id to students (single class per student)
ALTER TABLE public.students
  ADD COLUMN IF NOT EXISTS class_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'students_class_id_fkey'
  ) THEN
    ALTER TABLE public.students
      ADD CONSTRAINT students_class_id_fkey FOREIGN KEY (class_id)
      REFERENCES public.classes(class_id);
  END IF;
END $$;

-- 5) Add student_count to classes for cached class size
ALTER TABLE public.classes
  ADD COLUMN IF NOT EXISTS student_count integer DEFAULT 0;

-- Backfill student_count from students table
UPDATE public.classes c
SET student_count = COALESCE(s.cnt, 0)
FROM (
  SELECT class_id, COUNT(*) AS cnt
  FROM public.students
  WHERE class_id IS NOT NULL
  GROUP BY class_id
) s
WHERE c.class_id = s.class_id;

-- 6) Enforce room capacity (set missing to 1 then NOT NULL)
UPDATE public.rooms
SET capacity = 1
WHERE capacity IS NULL;

ALTER TABLE public.rooms
  ALTER COLUMN capacity SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'rooms_capacity_positive'
  ) THEN
    ALTER TABLE public.rooms
      ADD CONSTRAINT rooms_capacity_positive CHECK (capacity > 0);
  END IF;
END $$;

-- 7) Optional: department_id foreign keys on staff and subjects_master (only if departments used)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'staff_department_id_fkey'
  ) THEN
    ALTER TABLE public.staff
      ADD CONSTRAINT staff_department_id_fkey FOREIGN KEY (department_id)
      REFERENCES public.departments(department_id);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'subjects_master_department_id_fkey'
  ) THEN
    ALTER TABLE public.subjects_master
      ADD CONSTRAINT subjects_master_department_id_fkey FOREIGN KEY (department_id)
      REFERENCES public.departments(department_id);
  END IF;
END $$;

-- Note:
-- After migrating, set students.class_id for existing records, then optionally enforce NOT NULL:
-- ALTER TABLE public.students ALTER COLUMN class_id SET NOT NULL;
